# Uncomment the next line to define a global platform for your project

target 'AnalyticsKit' do
  platform :ios, '8.4'
  use_frameworks!

  # Pods for AnalyticsKit

  pod 'GoogleAnalytics'
  pod 'Crashlytics'


  target 'AnalyticsKitTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'OCMock'
  end

end
